name: Patreon RSS Feed updater

permissions:
  contents: write

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes

  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run python script
        env:
          PATREON_RSS_URL: ${{ secrets.PATREON_RSS_URL }}
        run: python update_feed.py

      - name: Commit feed.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config pull.rebase false
          git pull origin main || true
          git add feed.xml
          git diff --cached --quiet || git commit -m "Updated the RSS feed with new posts"
          git push
